# Pre-commit hooks for ST-AYGENT
# Ensures code quality before commits!

repos:
  # Black - The uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        files: '^(feedback-api|feedback-worker)/.*\.py$'

  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
        files: '^(feedback-api|feedback-worker)/.*\.py$'

  # Check YAML files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1000']

# To install: pip install pre-commit && pre-commit install
# To run manually: pre-commit run --all-files